(function (global) {
  'use strict';

  // Sutra Sheets' deterministic model. Coordinates are a presentation layer;
  // durable cells are keyed by stable row and column ids so structural edits do
  // not change their identity.
  var ERROR = { REF: '#REF!', VALUE: '#VALUE!', DIV0: '#DIV/0!', NAME: '#NAME?', NA: '#N/A', CYCLE: '#CYCLE!' };
  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function id(prefix) { return (prefix || 'sheet') + '_' + Math.random().toString(36).slice(2, 10) + Date.now().toString(36); }
  function columnLabel(index) { var text = ''; var n = Number(index) + 1; while (n > 0) { var r = (n - 1) % 26; text = String.fromCharCode(65 + r) + text; n = Math.floor((n - 1) / 26); } return text; }
  function columnIndex(label) { var value = 0; var source = String(label || '').toUpperCase(); if (!/^[A-Z]+$/.test(source)) return -1; for (var i = 0; i < source.length; i += 1) value = value * 26 + source.charCodeAt(i) - 64; return value - 1; }
  function parseA1(text) { var match = /^\$?([A-Z]+)\$?([1-9]\d*)$/i.exec(String(text || '').trim()); return match ? { col: columnIndex(match[1]), row: Number(match[2]) - 1, colAbsolute: text.indexOf('$' + match[1]) !== -1, rowAbsolute: /\$\d+$/.test(text) } : null; }
  function a1(ref) { return (ref.colAbsolute ? '$' : '') + columnLabel(ref.col) + (ref.rowAbsolute ? '$' : '') + String(ref.row + 1); }
  function createSheet(name, options) { var o = options || {}; var rows = []; var columns = []; var rowCount = Math.max(1, Number(o.rowCount) || 200); var columnCount = Math.max(1, Number(o.columnCount) || 26); for (var r = 0; r < rowCount; r += 1) rows.push({ id: id('row'), height: 28, hidden: false }); for (var c = 0; c < columnCount; c += 1) columns.push({ id: id('col'), width: 120, hidden: false }); return { id: id('sheet'), name: String(name || 'Sheet'), rows: rows, columns: columns, cells: {}, merges: [], frozen: { rows: 0, columns: 0 }, filters: [], conditionalFormats: [], charts: [] }; }
  function createWorkbook(title) { return { version: 2, title: String(title || 'Untitled workbook'), sheets: [createSheet('Sheet1')], namedRanges: {}, styles: {}, importWarnings: [] }; }
  function isCellMeaningful(cell) { return !!(cell && (cell.value !== '' || cell.formula || cell.styleId || cell.note || cell.validation)); }
  function normalizeSheet(raw, index) {
    var source = raw && typeof raw === 'object' ? raw : {};
    var sheet = Object.assign({}, source, {
      id: String(source.id || id('sheet')),
      name: String(source.name || ('Sheet' + (index + 1))).slice(0, 100),
      rows: Array.isArray(source.rows) ? source.rows : [],
      columns: Array.isArray(source.columns) ? source.columns : [],
      cells: {},
      merges: Array.isArray(source.merges) ? clone(source.merges) : [],
      frozen: source.frozen && typeof source.frozen === 'object' ? clone(source.frozen) : { rows: 0, columns: 0 },
      filters: Array.isArray(source.filters) ? clone(source.filters) : [],
      conditionalFormats: Array.isArray(source.conditionalFormats) ? clone(source.conditionalFormats) : [],
      charts: Array.isArray(source.charts) ? clone(source.charts) : []
    });
    if (!sheet.rows.length) sheet.rows = createSheet('', { rowCount: 200, columnCount: 1 }).rows;
    if (!sheet.columns.length) sheet.columns = createSheet('', { rowCount: 1, columnCount: 26 }).columns;
    sheet.rows = sheet.rows.map(function (row) { return Object.assign({}, row && typeof row === 'object' ? row : {}, { id: String(row && row.id || id('row')), height: Math.max(20, Math.min(200, Number(row && row.height) || 28)), hidden: !!(row && row.hidden) }); });
    sheet.columns = sheet.columns.map(function (column) { return Object.assign({}, column && typeof column === 'object' ? column : {}, { id: String(column && column.id || id('col')), width: Math.max(44, Math.min(600, Number(column && column.width) || 120)), hidden: !!(column && column.hidden) }); });
    Object.keys(source.cells && typeof source.cells === 'object' ? source.cells : {}).forEach(function (key) { var cell = source.cells[key]; if (!cell || typeof cell !== 'object') return; var bits = key.split(':'); if (!sheet.rows.some(function (r) { return r.id === bits[0]; }) || !sheet.columns.some(function (c) { return c.id === bits[1]; })) return; var normalized = Object.assign({}, cell, { value: cell.value == null ? '' : cell.value, formula: typeof cell.formula === 'string' ? cell.formula.slice(0, 10000) : '', styleId: typeof cell.styleId === 'string' ? cell.styleId : '', note: typeof cell.note === 'string' ? cell.note.slice(0, 10000) : '', validation: cell.validation && typeof cell.validation === 'object' ? clone(cell.validation) : null }); if (isCellMeaningful(normalized)) sheet.cells[key] = normalized; });
    sheet.frozen = { rows: Math.max(0, Math.min(sheet.rows.length, Math.floor(Number(sheet.frozen.rows) || 0))), columns: Math.max(0, Math.min(sheet.columns.length, Math.floor(Number(sheet.frozen.columns) || 0))) };
    return sheet;
  }
  function normalizeWorkbook(raw, title) { var source = raw && typeof raw === 'object' ? raw : {}; var sheets = Array.isArray(source.sheets) ? source.sheets.map(normalizeSheet) : []; if (!sheets.length) sheets = [createSheet('Sheet1')]; return Object.assign({}, source, { version: 2, title: String(source.title || title || 'Untitled workbook').slice(0, 200), sheets: sheets, namedRanges: source.namedRanges && typeof source.namedRanges === 'object' ? clone(source.namedRanges) : {}, styles: source.styles && typeof source.styles === 'object' ? clone(source.styles) : {}, importWarnings: Array.isArray(source.importWarnings) ? source.importWarnings.map(String).slice(0, 100) : [] }); }
  function cellKey(sheet, rowIndex, colIndex) { return sheet.rows[rowIndex] && sheet.columns[colIndex] ? sheet.rows[rowIndex].id + ':' + sheet.columns[colIndex].id : ''; }
  function cellAt(sheet, row, col) { return sheet && sheet.cells[cellKey(sheet, row, col)] || null; }
  function setCell(sheet, row, col, next) { var key = cellKey(sheet, row, col); if (!key) return false; var cell = Object.assign({ value: '', formula: '', styleId: '', note: '', validation: null }, next || {}); if (isCellMeaningful(cell)) sheet.cells[key] = cell; else delete sheet.cells[key]; return true; }
  function sheetByName(workbook, name) { var needle = String(name || '').replace(/^'|'$/g, ''); return workbook.sheets.find(function (sheet) { return sheet.name === needle; }) || null; }
  function toScalar(value) { if (value && value.error) return value; if (value === null || value === undefined || value === '') return 0; if (typeof value === 'boolean' || typeof value === 'number') return value; var numeric = Number(value); return Number.isFinite(numeric) && String(value).trim() !== '' ? numeric : value; }
  function flatten(values) { return values.reduce(function (out, value) { return out.concat(Array.isArray(value) ? flatten(value) : [value]); }, []); }
  function error(value) { return { error: value }; }
  function isError(value) { return !!(value && value.error); }
  function numeric(value) { var n = Number(value); return Number.isFinite(n) ? n : null; }
  function criterion(value, rule) { var text = String(rule == null ? '' : rule); var match = /^(<=|>=|<>|=|<|>)(.*)$/.exec(text); var left = value == null ? '' : value; if (!match) return String(left).toLowerCase() === text.toLowerCase(); var right = match[2]; var a = numeric(left); var b = numeric(right); var compare = a !== null && b !== null ? a - b : String(left).localeCompare(right); return ({ '=': compare === 0, '<>': compare !== 0, '>': compare > 0, '<': compare < 0, '>=': compare >= 0, '<=': compare <= 0 })[match[1]]; }
  function tokenize(formula) {
    var source = String(formula || '').replace(/^=/, ''); var tokens = []; var re = /\s*(?:(\d+(?:\.\d+)?)|("(?:[^"]|"")*")|((?:'[^']+'|[A-Za-z_][\w.]*)?!?\$?[A-Za-z]+\$?[1-9]\d*(?::(?:'[^']+'|[A-Za-z_][\w.]*)?!?\$?[A-Za-z]+\$?[1-9]\d*)?)|([A-Za-z_][A-Za-z0-9_.]*)|(<=|>=|<>|[+\-*/^&=<>(),:]))/g; var index = 0; var match; while ((match = re.exec(source))) { if (match.index !== index) throw error(ERROR.VALUE); index = re.lastIndex; tokens.push({ type: match[1] ? 'number' : match[2] ? 'string' : match[3] ? 'ref' : match[4] ? 'name' : 'operator', value: match[1] || match[2] || match[3] || match[4] || match[5] }); } if (index !== source.length) throw error(ERROR.VALUE); return tokens; }
  function parseFormula(formula) {
    var tokens = tokenize(formula); var cursor = 0;
    function peek() { return tokens[cursor]; } function eat(value) { var token = peek(); if (token && token.value === value) { cursor += 1; return true; } return false; }
    function primary() { var token = tokens[cursor++]; if (!token) throw error(ERROR.VALUE); if (token.type === 'number') return { type: 'literal', value: Number(token.value) }; if (token.type === 'string') return { type: 'literal', value: token.value.slice(1, -1).replace(/""/g, '"') }; if (token.type === 'ref') return { type: 'ref', value: token.value }; if (token.type === 'name') { if (eat('(')) { var args = []; if (!eat(')')) { do { args.push(expression()); } while (eat(',')); if (!eat(')')) throw error(ERROR.VALUE); } return { type: 'call', name: token.value.toUpperCase(), args: args }; } if (token.value.toUpperCase() === 'TRUE') return { type: 'literal', value: true }; if (token.value.toUpperCase() === 'FALSE') return { type: 'literal', value: false }; return { type: 'name', value: token.value }; } if (token.value === '(') { var node = expression(); if (!eat(')')) throw error(ERROR.VALUE); return node; } if (token.value === '-') return { type: 'unary', op: '-', value: primary() }; throw error(ERROR.VALUE); }
    function power() { var left = primary(); while (eat('^')) left = { type: 'binary', op: '^', left: left, right: power() }; return left; }
    function product() { var left = power(); while (peek() && (peek().value === '*' || peek().value === '/')) { var op = tokens[cursor++].value; left = { type: 'binary', op: op, left: left, right: power() }; } return left; }
    function sum() { var left = product(); while (peek() && (peek().value === '+' || peek().value === '-' || peek().value === '&')) { var op = tokens[cursor++].value; left = { type: 'binary', op: op, left: left, right: product() }; } return left; }
    function comparison() { var left = sum(); if (peek() && /^(=|<>|<|>|<=|>=)$/.test(peek().value)) { var op = tokens[cursor++].value; left = { type: 'binary', op: op, left: left, right: sum() }; } return left; }
    function expression() { return comparison(); } var root = expression(); if (cursor !== tokens.length) throw error(ERROR.VALUE); return root;
  }
  function parseReference(text, currentSheet, workbook) { var source = String(text || ''); var bang = source.lastIndexOf('!'); var sheet = currentSheet; if (bang !== -1) { sheet = sheetByName(workbook, source.slice(0, bang)); source = source.slice(bang + 1); if (!sheet) return error(ERROR.REF); } var parts = source.split(':'); var start = parseA1(parts[0]); var end = parts[1] ? parseA1(parts[1]) : start; if (!start || !end || start.row >= sheet.rows.length || start.col >= sheet.columns.length || end.row >= sheet.rows.length || end.col >= sheet.columns.length) return error(ERROR.REF); return { sheet: sheet, start: start, end: end }; }
  function evaluate(workbook) {
    var cache = {}; var visiting = {};
    function getValue(sheet, row, col) { var key = sheet.id + ':' + cellKey(sheet, row, col); if (Object.prototype.hasOwnProperty.call(cache, key)) return cache[key]; if (visiting[key]) return error(ERROR.CYCLE); visiting[key] = true; var cell = cellAt(sheet, row, col); var result = cell && cell.formula ? runFormula(cell.formula, sheet) : toScalar(cell ? cell.value : ''); delete visiting[key]; cache[key] = result; return result; }
    function refValue(text, sheet) { var parsed = parseReference(text, sheet, workbook); if (isError(parsed)) return parsed; var values = []; for (var row = Math.min(parsed.start.row, parsed.end.row); row <= Math.max(parsed.start.row, parsed.end.row); row += 1) for (var col = Math.min(parsed.start.col, parsed.end.col); col <= Math.max(parsed.start.col, parsed.end.col); col += 1) values.push(getValue(parsed.sheet, row, col)); return values.length === 1 ? values[0] : values; }
    function fn(name, args) { var flat = flatten(args); var firstError = flat.find(isError); if (firstError && name !== 'IFERROR') return firstError; var nums = flat.map(numeric).filter(function (n) { return n !== null; }); var values = flat.filter(function (v) { return !isError(v); }); var single = function (i) { return Array.isArray(args[i]) ? args[i][0] : args[i]; };
      if (name === 'SUM') return nums.reduce(function (a, b) { return a + b; }, 0); if (name === 'AVERAGE') return nums.length ? nums.reduce(function (a, b) { return a + b; }, 0) / nums.length : error(ERROR.DIV0); if (name === 'MIN') return nums.length ? Math.min.apply(Math, nums) : 0; if (name === 'MAX') return nums.length ? Math.max.apply(Math, nums) : 0; if (name === 'COUNT') return nums.length; if (name === 'COUNTA') return values.filter(function (v) { return v !== ''; }).length;
      if (name === 'ROUND' || name === 'ROUNDUP' || name === 'ROUNDDOWN') { var value = numeric(single(0)); var digits = numeric(single(1)); if (value === null || digits === null) return error(ERROR.VALUE); var factor = Math.pow(10, digits); return name === 'ROUND' ? Math.round(value * factor) / factor : (name === 'ROUNDUP' ? (value < 0 ? Math.floor(value * factor) : Math.ceil(value * factor)) : (value < 0 ? Math.ceil(value * factor) : Math.floor(value * factor))) / factor; }
      if (name === 'ABS') return Math.abs(numeric(single(0)) || 0); if (name === 'MOD') { var divisor = numeric(single(1)); return divisor ? (numeric(single(0)) || 0) % divisor : error(ERROR.DIV0); }
      if (name === 'IF') return single(0) ? single(1) : (args.length > 2 ? single(2) : false); if (name === 'IFS') { for (var i = 0; i < args.length; i += 2) if (single(i)) return single(i + 1); return error(ERROR.NA); } if (name === 'AND') return values.every(Boolean); if (name === 'OR') return values.some(Boolean); if (name === 'NOT') return !single(0); if (name === 'IFERROR') return isError(single(0)) ? single(1) : single(0);
      if (name === 'LEFT') return String(single(0) || '').slice(0, numeric(single(1)) == null ? 1 : numeric(single(1))); if (name === 'RIGHT') { var s = String(single(0) || ''); return s.slice(-(numeric(single(1)) == null ? 1 : numeric(single(1)))); } if (name === 'MID') return String(single(0) || '').slice(Math.max(0, (numeric(single(1)) || 1) - 1), numeric(single(2)) || 0); if (name === 'LEN') return String(single(0) || '').length; if (name === 'CONCAT' || name === 'CONCATENATE') return values.join(''); if (name === 'TEXTJOIN') return values.slice(2).filter(function (v) { return !single(1) || v !== ''; }).join(String(single(0) || '')); if (name === 'TRIM') return String(single(0) || '').trim().replace(/\s+/g, ' '); if (name === 'UPPER') return String(single(0) || '').toUpperCase(); if (name === 'LOWER') return String(single(0) || '').toLowerCase(); if (name === 'PROPER') return String(single(0) || '').replace(/\b\w/g, function (c) { return c.toUpperCase(); });
      if (name === 'DATE') return new Date(Number(single(0)), Number(single(1)) - 1, Number(single(2))).toISOString().slice(0, 10); if (name === 'TODAY') return new Date().toISOString().slice(0, 10); if (name === 'NOW') return new Date().toISOString(); if (name === 'YEAR' || name === 'MONTH' || name === 'DAY') { var d = new Date(single(0)); if (isNaN(d)) return error(ERROR.VALUE); return name === 'YEAR' ? d.getFullYear() : name === 'MONTH' ? d.getMonth() + 1 : d.getDate(); }
      if (name === 'COUNTIF' || name === 'SUMIF' || name === 'AVERAGEIF') { var candidates = Array.isArray(args[0]) ? args[0] : [args[0]]; var matches = candidates.filter(function (v) { return criterion(v, single(1)); }); if (name === 'COUNTIF') return matches.length; var range = Array.isArray(args[2]) ? args[2] : candidates; var picked = range.filter(function (_, index) { return criterion(candidates[index], single(1)); }).map(numeric).filter(function (n) { return n !== null; }); return name === 'SUMIF' ? picked.reduce(function (a, b) { return a + b; }, 0) : (picked.length ? picked.reduce(function (a, b) { return a + b; }, 0) / picked.length : error(ERROR.DIV0)); }
      if (name === 'VLOOKUP' || name === 'HLOOKUP') { var lookup = single(0); var table = Array.isArray(args[1]) ? args[1] : [args[1]]; var index = Math.floor(numeric(single(2)) || 1) - 1; if (name === 'VLOOKUP') { for (var vi = 0; vi < table.length; vi += 1) if (String(table[vi]) === String(lookup)) return table[vi + index] === undefined ? error(ERROR.REF) : table[vi + index]; } return error(ERROR.NA); }
      if (name === 'MEDIAN') { if (!nums.length) return error(ERROR.DIV0); nums.sort(function (a, b) { return a - b; }); var middle = Math.floor(nums.length / 2); return nums.length % 2 ? nums[middle] : (nums[middle - 1] + nums[middle]) / 2; }
      if (name === 'STDEV' || name === 'STDEV.S' || name === 'VAR' || name === 'VAR.S') { if (nums.length < 2) return error(ERROR.DIV0); var mean = nums.reduce(function (a, b) { return a + b; }, 0) / nums.length; var variance = nums.reduce(function (sum, n) { return sum + Math.pow(n - mean, 2); }, 0) / (nums.length - 1); return name.indexOf('STDEV') === 0 ? Math.sqrt(variance) : variance; }
      if (name === 'MATCH') { var needle = single(0); var matchRange = Array.isArray(args[1]) ? args[1] : [args[1]]; var matchIndex = matchRange.findIndex(function (item) { return String(item) === String(needle); }); return matchIndex < 0 ? error(ERROR.NA) : matchIndex + 1; }
      if (name === 'INDEX') { var indexRange = Array.isArray(args[0]) ? args[0] : [args[0]]; var position = Math.max(0, Math.floor(numeric(single(1)) || 1) - 1); return indexRange[position] === undefined ? error(ERROR.REF) : indexRange[position]; }
      if (name === 'XLOOKUP') { var xNeedle = single(0); var lookupRange = Array.isArray(args[1]) ? args[1] : [args[1]]; var returnRange = Array.isArray(args[2]) ? args[2] : [args[2]]; var found = lookupRange.findIndex(function (item) { return String(item) === String(xNeedle); }); return found < 0 ? (args.length > 3 ? single(3) : error(ERROR.NA)) : (returnRange[found] === undefined ? error(ERROR.REF) : returnRange[found]); }
      if (name === 'FIND' || name === 'SEARCH') { var needleText = String(single(0) || ''); var haystackText = String(single(1) || ''); var startAt = Math.max(0, (numeric(single(2)) || 1) - 1); var located = name === 'SEARCH' ? haystackText.toLowerCase().indexOf(needleText.toLowerCase(), startAt) : haystackText.indexOf(needleText, startAt); return located < 0 ? error(ERROR.VALUE) : located + 1; }
      if (name === 'SUBSTITUTE') return String(single(0) || '').split(String(single(1) || '')).join(String(single(2) || ''));
      if (name === 'WEEKDAY') { var weekdayDate = new Date(single(0)); return isNaN(weekdayDate) ? error(ERROR.VALUE) : weekdayDate.getDay() + 1; }
      if (name === 'XOR') return values.filter(Boolean).length % 2 === 1;
      return error(ERROR.NAME);
    }
    function visit(node, sheet) { if (!node) return error(ERROR.VALUE); if (node.type === 'literal') return node.value; if (node.type === 'name') { var named = workbook.namedRanges && workbook.namedRanges[node.value]; return named ? refValue(named, sheet) : error(ERROR.NAME); } if (node.type === 'ref') return refValue(node.value, sheet); if (node.type === 'unary') { var unary = visit(node.value, sheet); var un = numeric(unary); return isError(unary) || un === null ? error(ERROR.VALUE) : -un; } if (node.type === 'call') return fn(node.name, node.args.map(function (arg) { return visit(arg, sheet); })); var left = visit(node.left, sheet); var right = visit(node.right, sheet); if (isError(left)) return left; if (isError(right)) return right; left = Array.isArray(left) ? left[0] : left; right = Array.isArray(right) ? right[0] : right; var a = numeric(left); var b = numeric(right); if (node.op === '&') return String(left) + String(right); if (/^(=|<>|<|>|<=|>=)$/.test(node.op)) return criterion(left, node.op + right); if (a === null || b === null) return error(ERROR.VALUE); if (node.op === '+') return a + b; if (node.op === '-') return a - b; if (node.op === '*') return a * b; if (node.op === '/') return b === 0 ? error(ERROR.DIV0) : a / b; if (node.op === '^') return Math.pow(a, b); return error(ERROR.VALUE); }
    function runFormula(formula, sheet) { try { return visit(parseFormula(formula), sheet); } catch (err) { return err && err.error ? err : error(ERROR.VALUE); } }
    return { getValue: getValue, values: cache };
  }
  function translateFormula(formula, rowDelta, colDelta) { return String(formula || '').replace(/((?:'[^']+'|[A-Za-z_][\w.]*)!)?(\$?[A-Z]+)(\$?)([1-9]\d*)/g, function (_, prefix, column, rowMarker, row) { var colAbsolute = column.charAt(0) === '$'; var baseCol = columnIndex(column.replace('$', '')); var baseRow = Number(row) - 1; var targetCol = colAbsolute ? baseCol : baseCol + colDelta; var targetRow = rowMarker === '$' ? baseRow : baseRow + rowDelta; if (targetCol < 0 || targetRow < 0) return '#REF!'; return (prefix || '') + (colAbsolute ? '$' : '') + columnLabel(targetCol) + (rowMarker || '') + (targetRow + 1); }); }
  function rewriteFormulaForStructure(formula, axis, index, delta) {
    var change = Number(delta) || 0; var at = Math.max(0, Math.floor(Number(index) || 0)); if (!change) return String(formula || '');
    return String(formula || '').replace(/((?:'[^']+'|[A-Za-z_][\w.]*)!)?(\$?)([A-Z]+)(\$?)([1-9]\d*)/g, function (_, prefix, colMarker, column, rowMarker, rowText) {
      var row = Number(rowText) - 1; var col = columnIndex(column); var target = axis === 'column' ? col : row;
      if (change < 0 && target >= at && target < at + Math.abs(change)) return '#REF!';
      if (target >= at + (change < 0 ? Math.abs(change) : 0)) target += change;
      if (target < 0) return '#REF!';
      if (axis === 'column') col = target; else row = target;
      return (prefix || '') + colMarker + columnLabel(col) + rowMarker + String(row + 1);
    });
  }
  function rewriteWorkbookFormulas(workbook, axis, index, delta) {
    (workbook && workbook.sheets || []).forEach(function (sheet) { Object.keys(sheet.cells || {}).forEach(function (key) { var cell = sheet.cells[key]; if (cell && cell.formula) cell.formula = rewriteFormulaForStructure(cell.formula, axis, index, delta); }); });
    Object.keys(workbook && workbook.namedRanges || {}).forEach(function (name) { workbook.namedRanges[name] = rewriteFormulaForStructure(workbook.namedRanges[name], axis, index, delta); });
    return workbook;
  }
  function dependencies(workbook, sheet, formula) { var refs = String(formula || '').match(/(?:'(?:[^']+)'|[A-Za-z_][\w.]*)?!?\$?[A-Z]+\$?[1-9]\d*(?::(?:'(?:[^']+)'|[A-Za-z_][\w.]*)?!?\$?[A-Z]+\$?[1-9]\d*)?/g) || []; var out = []; refs.forEach(function (ref) { var parsed = parseReference(ref, sheet, workbook); if (isError(parsed)) return; for (var r = Math.min(parsed.start.row, parsed.end.row); r <= Math.max(parsed.start.row, parsed.end.row); r += 1) for (var c = Math.min(parsed.start.col, parsed.end.col); c <= Math.max(parsed.start.col, parsed.end.col); c += 1) out.push(parsed.sheet.id + ':' + cellKey(parsed.sheet, r, c)); }); return out; }
  var api = { ERROR: ERROR, id: id, createSheet: createSheet, createWorkbook: createWorkbook, normalizeWorkbook: normalizeWorkbook, columnLabel: columnLabel, columnIndex: columnIndex, parseA1: parseA1, a1: a1, cellKey: cellKey, cellAt: cellAt, setCell: setCell, evaluate: evaluate, parseFormula: parseFormula, translateFormula: translateFormula, rewriteFormulaForStructure: rewriteFormulaForStructure, rewriteWorkbookFormulas: rewriteWorkbookFormulas, dependencies: dependencies, clone: clone };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  if (global) global.SutraSheetsEngine = api;
}(typeof window !== 'undefined' ? window : globalThis));
