(function (global) {
  'use strict';
  var activePageId = ''; var activeSheetId = ''; var root = null; var selection = { row: 0, col: 0, anchorRow: 0, anchorCol: 0 }; var editing = false; var undo = []; var redo = []; var clipboard = null;
  function engine() { return global.SutraSheetsEngine; }
  function bridge() { var value = global.flowAtelier; if (!value || !Array.isArray(value.pages) || typeof value.persistAppData !== 'function') throw new Error('Sheets requires the canonical Sutra workspace bridge.'); return value; }
  function authorized(page) { var value = bridge(); return typeof value.isPageContentAuthorized === 'function' ? value.isPageContentAuthorized(page) : !!(page && !(page.isLocked && page.lockHash)); }
  function activePage() { var page = bridge().pages.find(function (item) { return item && item.id === activePageId; }) || null; return page && authorized(page) ? page : null; }
  function workbookFor(page) { return page && page.spreadsheet && Array.isArray(page.spreadsheet.sheets) ? page.spreadsheet : null; }
  function activeSheet(book) { return book && book.sheets.find(function (sheet) { return sheet.id === activeSheetId; }) || (book && book.sheets[0]) || null; }
  function visible(rootValue) { if (!rootValue) return; rootValue.hidden = false; rootValue.removeAttribute('inert'); rootValue.setAttribute('aria-hidden', 'false'); }
  function hidden(rootValue) { if (!rootValue) return; rootValue.hidden = true; rootValue.setAttribute('inert', ''); rootValue.setAttribute('aria-hidden', 'true'); }
  function displayValue(value) { return value && value.error ? value.error : (value == null ? '' : String(value)); }
  function sheetLimit(sheet, axis) { return axis === 'row' ? Math.max(10000, sheet.rows.length + 20) : Math.max(100, sheet.columns.length + 8); }
  function ensure(sheet, row, col) { var api = engine(); while (sheet.rows.length <= row) sheet.rows.push({ id: api.id('row'), height: 28 }); while (sheet.columns.length <= col) sheet.columns.push({ id: api.id('col'), width: 120 }); }
  function snapshot(page) { return { pageId: page.id, book: engine().clone(page.spreadsheet) }; }
  function save(change, options) { var page = activePage(); if (!page) return false; if (!options || options.history !== false) { undo.push(snapshot(page)); if (undo.length > 80) undo.shift(); redo = []; } change(page.spreadsheet, page); page.updatedAt = new Date().toISOString(); bridge().persistAppData(); render(); return true; }
  function undoChange() { var page = activePage(); var entry = undo.pop(); if (!page || !entry || entry.pageId !== page.id) return; redo.push(snapshot(page)); page.spreadsheet = entry.book; page.updatedAt = new Date().toISOString(); bridge().persistAppData(); render(); }
  function redoChange() { var page = activePage(); var entry = redo.pop(); if (!page || !entry || entry.pageId !== page.id) return; undo.push(snapshot(page)); page.spreadsheet = entry.book; page.updatedAt = new Date().toISOString(); bridge().persistAppData(); render(); }
  function address() { return engine().columnLabel(selection.col) + String(selection.row + 1); }
  function selectedRange() { return engine().columnLabel(Math.min(selection.col, selection.anchorCol)) + String(Math.min(selection.row, selection.anchorRow) + 1) + (selection.row === selection.anchorRow && selection.col === selection.anchorCol ? '' : ':' + engine().columnLabel(Math.max(selection.col, selection.anchorCol)) + String(Math.max(selection.row, selection.anchorRow) + 1)); }
  function select(row, col, extend) { selection.row = Math.max(0, row); selection.col = Math.max(0, col); if (!extend) { selection.anchorRow = selection.row; selection.anchorCol = selection.col; } render(); }
  function inputValue() { var page = activePage(); var sheet = activeSheet(workbookFor(page)); var cell = sheet && engine().cellAt(sheet, selection.row, selection.col); return cell ? (cell.formula || cell.value || '') : ''; }
  function commit(value) { var page = activePage(); var sheet = activeSheet(workbookFor(page)); if (!sheet) return; ensure(sheet, selection.row, selection.col); var source = String(value == null ? '' : value); save(function () { engine().setCell(sheet, selection.row, selection.col, { value: source.charAt(0) === '=' ? '' : source, formula: source.charAt(0) === '=' ? source : '', styleId: (engine().cellAt(sheet, selection.row, selection.col) || {}).styleId || '' }); }); editing = false; }
  function startEdit(seed) { if (!activeSheet(workbookFor(activePage()))) return; editing = true; var input = root.querySelector('[data-formula]'); input.value = seed == null ? inputValue() : seed; input.focus(); input.select(); }
  function mount() {
    if (root) return root;
    root = document.createElement('section'); root.id = 'sheetsEditor'; root.className = 'sheets-editor'; root.hidden = true; root.setAttribute('inert', ''); root.setAttribute('aria-hidden', 'true'); root.setAttribute('aria-label', 'Sutra Sheets editor');
    root.innerHTML = '<div class="sheets-tabs" role="tablist" aria-label="Notes mode"><span>Notepad</span><span>Canvas</span><span>Slides</span><strong aria-selected="true">Sheets</strong></div><div class="sheets-toolbar" role="toolbar"><button type="button" data-undo aria-label="Undo">↶</button><button type="button" data-redo aria-label="Redo">↷</button><button type="button" data-bold aria-label="Bold selected cells"><b>B</b></button><button type="button" data-add-row>Insert row</button><button type="button" data-add-col>Insert column</button><button type="button" data-freeze>Freeze top row</button><button type="button" data-copy>Copy</button><button type="button" data-paste>Paste</button></div><div class="sheets-formula"><output data-address aria-label="Selected range"></output><span aria-hidden="true">fx</span><input data-formula aria-label="Formula or value" autocomplete="off" spellcheck="false"></div><div class="sheets-grid-wrap" tabindex="0" aria-label="Spreadsheet grid"><div class="sheets-corner" aria-hidden="true"></div><div class="sheets-column-headings" aria-hidden="true"></div><div class="sheets-row-headings" aria-hidden="true"></div><div class="sheets-grid-canvas" role="grid" aria-label="Cells"></div></div><footer class="sheets-tabs-bar"><div data-sheet-tabs></div><button type="button" data-add-sheet aria-label="Add sheet">+</button></footer>'; // sutra-allow-html: reviewed static Sheets chrome; workbook values always use textContent.
    var container = document.getElementById('notesPrimaryPane'); if (container) container.appendChild(root);
    root.querySelector('[data-undo]').onclick = undoChange; root.querySelector('[data-redo]').onclick = redoChange; root.querySelector('[data-add-row]').onclick = function () { var sheet = activeSheet(workbookFor(activePage())); if (sheet) save(function () { sheet.rows.splice(selection.row + 1, 0, { id: engine().id('row'), height: 28 }); }); }; root.querySelector('[data-add-col]').onclick = function () { var sheet = activeSheet(workbookFor(activePage())); if (sheet) save(function () { sheet.columns.splice(selection.col + 1, 0, { id: engine().id('col'), width: 120 }); }); }; root.querySelector('[data-freeze]').onclick = function () { var sheet = activeSheet(workbookFor(activePage())); if (sheet) save(function () { sheet.frozen.rows = sheet.frozen.rows ? 0 : 1; }); };
    root.querySelector('[data-bold]').onclick = function () { var sheet = activeSheet(workbookFor(activePage())); if (!sheet) return; var cell = engine().cellAt(sheet, selection.row, selection.col) || {}; save(function (book) { var styleId = cell.styleId === 'bold' ? '' : 'bold'; if (styleId) book.styles.bold = { fontWeight: '700' }; engine().setCell(sheet, selection.row, selection.col, Object.assign({}, cell, { styleId: styleId })); }); };
    root.querySelector('[data-formula]').addEventListener('keydown', function (event) { if (event.key === 'Enter') { event.preventDefault(); commit(event.target.value); select(selection.row + (event.shiftKey ? -1 : 1), selection.col); } if (event.key === 'Escape') { editing = false; render(); root.querySelector('.sheets-grid-wrap').focus(); } }); root.querySelector('[data-formula]').addEventListener('blur', function (event) { if (editing) commit(event.target.value); });
    root.querySelector('[data-copy]').onclick = copy; root.querySelector('[data-paste]').onclick = function () { if (navigator.clipboard && navigator.clipboard.readText) navigator.clipboard.readText().then(paste); else paste(clipboard || ''); }; root.querySelector('[data-add-sheet]').onclick = addSheet;
    root.querySelector('.sheets-grid-wrap').addEventListener('scroll', renderGrid); root.querySelector('.sheets-grid-wrap').addEventListener('dblclick', function () { startEdit(); }); root.querySelector('.sheets-grid-wrap').addEventListener('keydown', keys); return root;
  }
  function renderGrid() {
    if (!root || root.hidden) return; var page = activePage(); var book = workbookFor(page); var sheet = activeSheet(book); if (!sheet) return; var wrap = root.querySelector('.sheets-grid-wrap'); var canvas = root.querySelector('.sheets-grid-canvas'); var columns = root.querySelector('.sheets-column-headings'); var rows = root.querySelector('.sheets-row-headings'); var rowHeight = 28; var scrollTop = wrap.scrollTop; var scrollLeft = wrap.scrollLeft; var firstRow = Math.max(0, Math.floor(scrollTop / rowHeight) - 4); var lastRow = Math.min(sheetLimit(sheet, 'row'), Math.ceil((scrollTop + wrap.clientHeight) / rowHeight) + 5); var firstCol = Math.max(0, Math.floor(scrollLeft / 120) - 2); var lastCol = Math.min(sheetLimit(sheet, 'column'), Math.ceil((scrollLeft + wrap.clientWidth) / 120) + 3); var evaluation = engine().evaluate(book); canvas.replaceChildren(); columns.replaceChildren(); rows.replaceChildren(); canvas.style.width = (sheetLimit(sheet, 'column') * 120) + 'px'; canvas.style.height = (sheetLimit(sheet, 'row') * rowHeight) + 'px';
    for (var c = firstCol; c < lastCol; c += 1) { var header = document.createElement('div'); header.className = 'sheets-col-head'; header.textContent = engine().columnLabel(c); header.style.left = (48 + c * 120) + 'px'; header.style.width = '120px'; columns.appendChild(header); }
    for (var r = firstRow; r < lastRow; r += 1) { var rowHead = document.createElement('div'); rowHead.className = 'sheets-row-head'; rowHead.textContent = String(r + 1); rowHead.style.top = (r * rowHeight) + 'px'; rows.appendChild(rowHead); for (c = firstCol; c < lastCol; c += 1) { (function (row, col) { var cell = document.createElement('div'); cell.className = 'sheets-cell' + (row === selection.row && col === selection.col ? ' selected' : '') + (row >= Math.min(selection.row, selection.anchorRow) && row <= Math.max(selection.row, selection.anchorRow) && col >= Math.min(selection.col, selection.anchorCol) && col <= Math.max(selection.col, selection.anchorCol) ? ' in-range' : ''); cell.setAttribute('role', 'gridcell'); cell.setAttribute('aria-label', engine().columnLabel(col) + String(row + 1)); cell.style.left = (col * 120) + 'px'; cell.style.top = (row * rowHeight) + 'px'; var item = engine().cellAt(sheet, row, col); cell.textContent = item && item.formula ? displayValue(evaluation.getValue(sheet, row, col)) : displayValue(item && item.value); if (item && item.styleId === 'bold') cell.style.fontWeight = '700'; cell.addEventListener('pointerdown', function (event) { select(row, col, event.shiftKey); wrap.focus(); }); canvas.appendChild(cell); }(r, c)); } }
  }
  function render() { if (!root || root.hidden) return; var book = workbookFor(activePage()); var sheet = activeSheet(book); if (!sheet) return; activeSheetId = sheet.id; root.querySelector('[data-address]').textContent = selectedRange(); if (!editing) root.querySelector('[data-formula]').value = inputValue(); var tabs = root.querySelector('[data-sheet-tabs]'); tabs.replaceChildren(); book.sheets.forEach(function (item) { var button = document.createElement('button'); button.type = 'button'; button.className = item.id === sheet.id ? 'active' : ''; button.textContent = item.name; button.setAttribute('aria-label', 'Open ' + item.name); button.onclick = function () { activeSheetId = item.id; selection = { row: 0, col: 0, anchorRow: 0, anchorCol: 0 }; render(); }; button.ondblclick = function () { var next = global.prompt('Sheet name', item.name); if (next && next.trim()) save(function () { item.name = next.trim().slice(0, 100); }); }; tabs.appendChild(button); }); renderGrid(); }
  function keys(event) { var command = event.ctrlKey || event.metaKey; if (command && event.key.toLowerCase() === 'z') { event.preventDefault(); event.shiftKey ? redoChange() : undoChange(); return; } if (command && event.key.toLowerCase() === 'y') { event.preventDefault(); redoChange(); return; } if (command && event.key.toLowerCase() === 'c') { event.preventDefault(); copy(); return; } if (command && event.key.toLowerCase() === 'v') { event.preventDefault(); if (navigator.clipboard && navigator.clipboard.readText) navigator.clipboard.readText().then(paste); return; } if (event.key === 'F2' || event.key === 'Enter') { event.preventDefault(); startEdit(); return; } if (event.key === 'Delete' || event.key === 'Backspace') { event.preventDefault(); commit(''); return; } var direction = { ArrowUp: [-1, 0], ArrowDown: [1, 0], ArrowLeft: [0, -1], ArrowRight: [0, 1], Tab: [0, event.shiftKey ? -1 : 1] }[event.key]; if (direction) { event.preventDefault(); select(selection.row + direction[0], selection.col + direction[1], event.shiftKey); return; } if (event.key.length === 1 && !event.altKey) { event.preventDefault(); startEdit(event.key); } }
  function copy() { var page = activePage(); var sheet = activeSheet(workbookFor(page)); if (!sheet) return; var evals = engine().evaluate(workbookFor(page)); var lines = []; for (var row = Math.min(selection.row, selection.anchorRow); row <= Math.max(selection.row, selection.anchorRow); row += 1) { var cells = []; for (var col = Math.min(selection.col, selection.anchorCol); col <= Math.max(selection.col, selection.anchorCol); col += 1) { var cell = engine().cellAt(sheet, row, col); cells.push(cell && cell.formula ? cell.formula : displayValue(cell && cell.value)); } lines.push(cells.join('\t')); } clipboard = lines.join('\n'); if (navigator.clipboard && navigator.clipboard.writeText) navigator.clipboard.writeText(clipboard).catch(function () {}); }
  function paste(text) { var values = String(text || '').replace(/\r/g, '').split('\n').filter(function (_, index, all) { return !(index === all.length - 1 && all[index] === ''); }).map(function (line) { return line.split('\t'); }); if (!values.length) return; var page = activePage(); var sheet = activeSheet(workbookFor(page)); if (!sheet) return; save(function () { values.forEach(function (row, rowOffset) { row.forEach(function (value, colOffset) { ensure(sheet, selection.row + rowOffset, selection.col + colOffset); engine().setCell(sheet, selection.row + rowOffset, selection.col + colOffset, { value: value.charAt(0) === '=' ? '' : value, formula: value.charAt(0) === '=' ? value : '' }); }); }); }); }
  function addSheet() { var book = workbookFor(activePage()); if (!book) return; save(function () { var next = engine().createSheet('Sheet' + (book.sheets.length + 1)); book.sheets.push(next); activeSheetId = next.id; }); }
  function refresh() { var value; try { value = bridge(); } catch (err) { return; } var pageId = value.currentPageId || ''; var page = value.pages.find(function (item) { return item && item.id === pageId; }); activePageId = pageId; var show = !!(page && authorized(page) && workbookFor(page)); if (show) { mount(); visible(root); render(); } else hidden(root); document.body.classList.toggle('sheets-page-active', show); }
  function createPage(title, options) { var value = bridge(); var now = new Date().toISOString(); var page = { id: engine().id('page'), title: title || 'Spreadsheet', type: 'note', content: '', blocks: [], icon: '▦', spaceId: value.getActiveSpaceId ? value.getActiveSpaceId() : 'default', createdAt: now, updatedAt: now, spreadsheet: engine().normalizeWorkbook(options && options.workbook, title) }; value.pages.push(page); value.persistAppData(); if (typeof value.renderPagesList === 'function') value.renderPagesList(); if (typeof global.loadPage === 'function') global.loadPage(page.id); return page; }
  function createFromNewPageDialog() { var input = document.getElementById('newPageName'); var modal = document.getElementById('newPageModal'); if (modal) modal.classList.remove('active'); return createPage(input && input.value || 'Spreadsheet'); }
  global.addEventListener('sutra:note-page-loaded', refresh); setInterval(refresh, 400);
  global.SutraSheets = { createPage: createPage, createFromNewPageDialog: createFromNewPageDialog, getCurrentPage: function () { return activePage(); }, getWorkbook: function () { return workbookFor(activePage()); }, undo: undoChange, redo: redoChange, normalizeWorkbook: function (model) { return engine().normalizeWorkbook(model); } };
}(window));
